In [1]:
import torch

In [7]:
import numpy as np

In [2]:
torch.__version__

'1.6.0'

In [3]:
torch.__file__

'/home/efefer/anaconda3/lib/python3.8/site-packages/torch/__init__.py'

# Tensor

`tensor` in PyTorch is very similar to NumPy's `ndarray`:

Construct a 5x3 matrix, uninitialized:

In [4]:
x = torch.empty(5,3)
x

tensor([[0.0000e+00, 0.0000e+00, 8.9683e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [3.0855e-41, 4.2725e-05, 1.0800e-05],
        [6.8624e-07, 2.6224e-09, 4.1579e+21]])

In [6]:
torch.zeros(5,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x_np = np.zeros((5,3))

In [11]:
x_np.dtype

dtype('float64')

The default `dtype` is `float32`:

In [12]:
x.dtype

torch.float32

Randomly initialized matrix:

In [13]:
x = torch.rand(5,3)
x

tensor([[5.1309e-01, 6.7343e-01, 7.7593e-04],
        [2.1827e-01, 7.8932e-01, 5.3307e-01],
        [2.4327e-01, 9.3756e-01, 1.7821e-01],
        [2.7933e-01, 8.2852e-01, 1.4773e-01],
        [1.0830e-01, 3.3868e-01, 7.9767e-01]])

Matrix filled with zeros and using `long` or `int64` datatype:

In [16]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [17]:
x.dtype

torch.int64

Construct a tensor directly from data:

In [18]:
x = torch.tensor([1.3, 3.4, 1.2])
x

tensor([1.3000, 3.4000, 1.2000])

In [19]:
x.shape

torch.Size([3])

Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user:

In [20]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [21]:
x = torch.randn_like(x, dtype=torch.torch.float)
x

tensor([[ 0.1867,  0.4972,  0.3801],
        [ 0.2896, -0.2242, -0.0229],
        [-1.4588, -1.7734,  1.1725],
        [ 0.2092, -1.3372,  0.5822],
        [-1.0613,  0.2303, -0.9545]])

In [23]:
x.dtype

torch.float32

In [22]:
x.size()

torch.Size([5, 3])

# Mathematical operations

Addition

In [24]:
x = torch.rand(5,3)
y = torch.rand(5,3)
x + y

tensor([[1.1623, 0.4991, 1.1193],
        [1.6601, 1.1759, 0.9970],
        [1.4807, 1.1730, 0.7124],
        [0.6374, 1.7228, 0.3398],
        [0.4793, 0.2529, 1.6384]])

In [25]:
torch.add(x, y)

tensor([[1.1623, 0.4991, 1.1193],
        [1.6601, 1.1759, 0.9970],
        [1.4807, 1.1730, 0.7124],
        [0.6374, 1.7228, 0.3398],
        [0.4793, 0.2529, 1.6384]])

In [26]:
res = torch.empty(5,3) # preallocate memory
torch.add(x, y, out=res) # preferred for memory reuse
res

tensor([[1.1623, 0.4991, 1.1193],
        [1.6601, 1.1759, 0.9970],
        [1.4807, 1.1730, 0.7124],
        [0.6374, 1.7228, 0.3398],
        [0.4793, 0.2529, 1.6384]])

In-place addition (menggunakan underscore, contoh `add_`, 

In [29]:
x = torch.rand(5,3)
y = torch.rand(5,3)
y.add_(x)
y

tensor([[1.5683, 1.2441, 0.9856],
        [1.6999, 1.1456, 0.3051],
        [0.9255, 1.2872, 0.8764],
        [1.7426, 1.2828, 1.5996],
        [0.7695, 1.4685, 1.0038]])

In [28]:
y = y + x

Any operation that mutates tensor in-place is post-fixed with an `_`.

# Standard NumPy-like indexing

In [30]:
x

tensor([[0.8872, 0.3615, 0.4485],
        [0.7913, 0.5204, 0.2542],
        [0.6352, 0.7657, 0.6991],
        [0.9809, 0.9976, 0.7137],
        [0.7062, 0.9494, 0.9781]])

In [31]:
x[:,1]

tensor([0.3615, 0.5204, 0.7657, 0.9976, 0.9494])

In [38]:
x[:,1].size()

torch.Size([5])

In [39]:
x[1,:]

tensor([0.7913, 0.5204, 0.2542])

Resizing: if you want to resize/reshape tensor, you can use `torch.view`:

In [40]:
x = torch.randn(4,4)
x

tensor([[ 0.0404,  1.3648, -0.8537, -0.4127],
        [ 0.6930, -2.8214,  3.1702,  0.6027],
        [-1.0818, -0.0727,  0.1130,  0.7539],
        [-1.2945, -0.8166,  0.3911,  0.3331]])

In [41]:
y = x.view(16)
y

tensor([ 0.0404,  1.3648, -0.8537, -0.4127,  0.6930, -2.8214,  3.1702,  0.6027,
        -1.0818, -0.0727,  0.1130,  0.7539, -1.2945, -0.8166,  0.3911,  0.3331])

In [42]:
torch.reshape(x, (16,))

tensor([ 0.0404,  1.3648, -0.8537, -0.4127,  0.6930, -2.8214,  3.1702,  0.6027,
        -1.0818, -0.0727,  0.1130,  0.7539, -1.2945, -0.8166,  0.3911,  0.3331])

In [43]:
z = x.view(-1,8) # the size -1 is inferred from other dimensions
z

tensor([[ 0.0404,  1.3648, -0.8537, -0.4127,  0.6930, -2.8214,  3.1702,  0.6027],
        [-1.0818, -0.0727,  0.1130,  0.7539, -1.2945, -0.8166,  0.3911,  0.3331]])

In [47]:
torch.reshape(x, (2,8))

tensor([[ 0.0404,  1.3648, -0.8537, -0.4127,  0.6930, -2.8214,  3.1702,  0.6027],
        [-1.0818, -0.0727,  0.1130,  0.7539, -1.2945, -0.8166,  0.3911,  0.3331]])

In [48]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

In [49]:
x

tensor([[ 0.0404,  1.3648, -0.8537, -0.4127],
        [ 0.6930, -2.8214,  3.1702,  0.6027],
        [-1.0818, -0.0727,  0.1130,  0.7539],
        [-1.2945, -0.8166,  0.3911,  0.3331]])

In [50]:
z[1,1] = 9999.0

In [51]:
z

tensor([[ 4.0386e-02,  1.3648e+00, -8.5366e-01, -4.1266e-01,  6.9302e-01,
         -2.8214e+00,  3.1702e+00,  6.0268e-01],
        [-1.0818e+00,  9.9990e+03,  1.1303e-01,  7.5391e-01, -1.2945e+00,
         -8.1662e-01,  3.9112e-01,  3.3309e-01]])

In [52]:
x

tensor([[ 4.0386e-02,  1.3648e+00, -8.5366e-01, -4.1266e-01],
        [ 6.9302e-01, -2.8214e+00,  3.1702e+00,  6.0268e-01],
        [-1.0818e+00,  9.9990e+03,  1.1303e-01,  7.5391e-01],
        [-1.2945e+00, -8.1662e-01,  3.9112e-01,  3.3309e-01]])

If you have one-element tensor, use `.item()` to get the value as a Python number

In [53]:
x = torch.randn(1)
x

tensor([0.7117])

In [54]:
x.item()

0.7116602063179016

# Converting a Torch tensor to a NumPy array

In [56]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [57]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

Try to modify `a`:

In [58]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [59]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [60]:
b[1] = 10.0

In [61]:
b

array([ 2., 10.,  2.,  2.,  2.], dtype=float32)

In [62]:
a

tensor([ 2., 10.,  2.,  2.,  2.])

In [64]:
import copy

In [65]:
c = copy.deepcopy(b)

In [66]:
c

array([ 2., 10.,  2.,  2.,  2.], dtype=float32)

In [67]:
c[1] = 9999

In [68]:
c

array([2.000e+00, 9.999e+03, 2.000e+00, 2.000e+00, 2.000e+00],
      dtype=float32)

In [69]:
b

array([ 2., 10.,  2.,  2.,  2.], dtype=float32)

# Converting NumPy array to Torch tensor:

In [71]:
import numpy as np

In [72]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [76]:
a.dtype

dtype('float64')

In [73]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

Modify `a`:

In [74]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

`b` is also modified:

In [75]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

# CUDA Tensors

Check if CUDA is available:

In [77]:
torch.cuda.is_available()

True

In [78]:
device = torch.device("cuda")
device

device(type='cuda')

Directly create a tensor on a GPU

In [79]:
x = torch.rand(5,3)
x

tensor([[0.7204, 0.4154, 0.8408],
        [0.9213, 0.3519, 0.1749],
        [0.0535, 0.5240, 0.2406],
        [0.9361, 0.7132, 0.2785],
        [0.6750, 0.9364, 0.8645]])

In [80]:
x.dtype

torch.float32

In [81]:
y = torch.ones_like(x, device=device)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

Printing out CUDA tensor, requires copy from GPU to CPU which is usually slow.

Another way:

In [82]:
x_gpu = x.to(device)

In [83]:
type(x_gpu)

torch.Tensor

In [84]:
x.device

device(type='cpu')

In [85]:
x_gpu.device

device(type='cuda', index=0)

In [86]:
y.device

device(type='cuda', index=0)

In [87]:
z = x_gpu + y

In [88]:
print(z)

tensor([[1.7204, 1.4154, 1.8408],
        [1.9213, 1.3519, 1.1749],
        [1.0535, 1.5240, 1.2406],
        [1.9361, 1.7132, 1.2785],
        [1.6750, 1.9364, 1.8645]], device='cuda:0')


In [89]:
z.dtype

torch.float32

Copy from GPU to CPU, with type conversion from float to double (float64):

In [90]:
z_cpu = z.to("cpu", torch.double)
z_cpu

tensor([[1.7204, 1.4154, 1.8408],
        [1.9213, 1.3519, 1.1749],
        [1.0535, 1.5240, 1.2406],
        [1.9361, 1.7132, 1.2785],
        [1.6750, 1.9364, 1.8645]], dtype=torch.float64)