In [1]:
import torch

In [2]:
torch.__version__

'1.6.0'

# Tensor

`tensor` in PyTorch is very similar to NumPy's `ndarray`:

Construct a 5x3 matrix, uninitialized:

In [9]:
x = torch.empty(5,3)
x

tensor([[-3.2981e+26,  3.0931e-41, -3.3015e+26],
        [ 3.0931e-41,  8.9683e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -3.3015e+26],
        [ 3.0931e-41, -2.0259e-10,  4.5724e-41],
        [-2.6579e-26, -7.7492e-22,  4.1855e-12]])

The default `dtype` is `float32`:

In [10]:
x.dtype

torch.float32

Randomly initialized matrix:

In [4]:
x = torch.rand(5,3)
x

tensor([[0.8071, 0.4540, 0.7961],
        [0.3216, 0.2013, 0.9518],
        [0.5113, 0.5519, 0.2554],
        [0.9405, 0.5739, 0.1530],
        [0.2987, 0.4985, 0.5502]])

Matrix filled with zeros and using `long` or `int64` datatype:

In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x.dtype

torch.int64

Construct a tensor directly from data:

In [7]:
x = torch.tensor([1.3, 3.4, 1.2])
x

tensor([1.3000, 3.4000, 1.2000])

Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user:

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [13]:
x = torch.randn_like(x, dtype=torch.torch.float)
x

tensor([[ 0.6829,  0.7415, -0.2413],
        [-1.2190, -0.2699, -0.3476],
        [-0.0167,  2.4751, -0.2793],
        [ 0.5315, -1.4274,  1.0762],
        [-0.5935, -0.1374, -0.4934]])

In [15]:
x.size()

torch.Size([5, 3])

# Operasi

Addition

In [16]:
x = torch.rand(5,3)
y = torch.rand(5,3)
x + y

tensor([[0.5434, 1.7275, 0.7841],
        [1.1729, 1.3077, 1.1413],
        [1.2756, 1.8459, 0.1412],
        [0.1050, 1.3537, 0.6258],
        [0.5366, 0.6696, 1.2352]])

In [17]:
torch.add(x, y)

tensor([[0.5434, 1.7275, 0.7841],
        [1.1729, 1.3077, 1.1413],
        [1.2756, 1.8459, 0.1412],
        [0.1050, 1.3537, 0.6258],
        [0.5366, 0.6696, 1.2352]])

In [18]:
res = torch.empty(5,3)
torch.add(x, y, out=res)
res

tensor([[0.5434, 1.7275, 0.7841],
        [1.1729, 1.3077, 1.1413],
        [1.2756, 1.8459, 0.1412],
        [0.1050, 1.3537, 0.6258],
        [0.5366, 0.6696, 1.2352]])

In-place addition

In [20]:
x = torch.rand(5,3)
y = torch.rand(5,3)
y.add_(x)
y

tensor([[1.1220, 0.9043, 1.1066],
        [0.4974, 0.6425, 0.7923],
        [1.5639, 0.4949, 1.0128],
        [0.3241, 1.1560, 0.7654],
        [0.9087, 0.9013, 0.8398]])

Any operation that mutates tensor in-place is post-fixed with an `_`.

Standard NumPy-like indexing

In [22]:
x

tensor([[0.6571, 0.2130, 0.7405],
        [0.4244, 0.0816, 0.4964],
        [0.8098, 0.2333, 0.5609],
        [0.2174, 0.8158, 0.4418],
        [0.7958, 0.6145, 0.3611]])

In [23]:
x[:,1]

tensor([0.2130, 0.0816, 0.2333, 0.8158, 0.6145])

In [25]:
x[:,1].size()

torch.Size([5])

Resizing: if you want to resize/reshape tensor, you can use `torch.view`:

In [28]:
x = torch.randn(4,4)
x

tensor([[ 0.2611, -0.2463, -0.9580, -0.7667],
        [-0.1567, -0.6521,  0.6366,  0.0808],
        [ 0.8040,  0.3393,  0.6555,  1.7772],
        [ 0.8506, -0.6199,  0.4587,  2.0616]])

In [29]:
y = x.view(16)
y

tensor([ 0.2611, -0.2463, -0.9580, -0.7667, -0.1567, -0.6521,  0.6366,  0.0808,
         0.8040,  0.3393,  0.6555,  1.7772,  0.8506, -0.6199,  0.4587,  2.0616])

In [30]:
z = x.view(-1,8) # the size -1 is inferred from other dimensions
z

tensor([[ 0.2611, -0.2463, -0.9580, -0.7667, -0.1567, -0.6521,  0.6366,  0.0808],
        [ 0.8040,  0.3393,  0.6555,  1.7772,  0.8506, -0.6199,  0.4587,  2.0616]])

In [31]:
x.size(), y.size(), z.size()

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))

If you have one-element tensor, use `.item()` to get the value as a Python number

In [33]:
x = torch.randn(1)
x

tensor([1.5884])

In [34]:
x.item()

1.5884230136871338

Converting a Torch tensor to a NumPy array

In [3]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [5]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

Try to modify `a`:

In [6]:
a.add_(1)
a, b

(tensor([2., 2., 2., 2., 2.]), array([2., 2., 2., 2., 2.], dtype=float32))

Converting NumPy array to Torch tensor:

In [8]:
import numpy as np

In [10]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [11]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

Modify `a`:

In [12]:
np.add(a, 1, out=a)
a

array([2., 2., 2., 2., 2.])

`b` is also modified:

In [13]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

# CUDA Tensors

Check if CUDA is available:

In [14]:
torch.cuda.is_available()

True

In [15]:
device = torch.device("cuda")
device

device(type='cuda')

Directly create a tensor on a GPU

In [17]:
x = torch.rand(5,3)
x

tensor([[0.7482, 0.4024, 0.9227],
        [0.5764, 0.3215, 0.6731],
        [0.2774, 0.0394, 0.7374],
        [0.3998, 0.1060, 0.2438],
        [0.3076, 0.8063, 0.0269]])

In [18]:
y = torch.ones_like(x, device=device)
y

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

Printing out CUDA tensor, requires copy grom GPU to CPU which is usually slow.

Another way:

In [19]:
x_gpu = x.to(device)

In [20]:
type(x_gpu)

torch.Tensor

In [22]:
x.device

device(type='cpu')

In [21]:
x_gpu.device

device(type='cuda', index=0)

In [23]:
y.device

device(type='cuda', index=0)

In [25]:
z = x_gpu + y

In [26]:
print(z)

tensor([[1.7482, 1.4024, 1.9227],
        [1.5764, 1.3215, 1.6731],
        [1.2774, 1.0394, 1.7374],
        [1.3998, 1.1060, 1.2438],
        [1.3076, 1.8063, 1.0269]], device='cuda:0')


In [27]:
z.dtype

torch.float32

Copy from GPU to CPU, with type conversion from float to double

In [28]:
z_cpu = z.to("cpu", torch.double)
z_cpu

tensor([[1.7482, 1.4024, 1.9227],
        [1.5764, 1.3215, 1.6731],
        [1.2774, 1.0394, 1.7374],
        [1.3998, 1.1060, 1.2438],
        [1.3076, 1.8063, 1.0269]], dtype=torch.float64)